/* A month of Facet Pro posts: what each says, and where its numbers come from.

   Three kinds, mixed through the month:
   - price   — one job, priced by the engine on the day (prices.js), always
               naming the house type and carrying the planning-estimate line;
   - reveal  — a demo house before and after, labelled an AI illustration,
               with no price (its price is not the visitor's house);
   - tip     — plain advice. General, true, and nothing about Facet Pro that
               the product does not do.

   No customer photographs or renders, ever: they are pictures of real homes,
   kept private by the privacy notice. Video posts are left for later — the
   launch video is still being decided, and Buffer's bulk upload takes images
   only. */

'use strict';

const { glazingRange, exteriorRange } = require('./prices');

const TYPE = { semi: 'a typical semi-detached house', terrace: 'a typical mid-terrace house', detached: 'a typical detached house' };

module.exports = [
  // ── week 1 ──
  { kind: 'reveal', slug: 'anthracite-reveal', before: 'pbBefore', after: 'pbAnth',
    headline: 'Same house. Anthracite windows.',
    sub: 'One photo of the front, new frames on your own house in about a minute.',
    caption: 'White uPVC to anthracite grey — on the same house, from one photo. This is how Facet Pro shows it before anyone comes round.',
    alt: 'Before and after AI illustration of a red-brick detached house: white windows on the left, anthracite grey windows on the right.',
    link: '/design?journey=windows', pinTitle: 'White to anthracite windows: before and after' },
  { kind: 'price', slug: '8-windows-semi',
    headline: '8 new windows', detail: 'uPVC casement · white',
    houseType: 'semi', price: () => glazingRange({ houseType: 'semi', count: 8 }),
    caption: (p) => `What do 8 new uPVC casement windows cost on ${TYPE.semi}? ${p} fitted, inc. VAT — taking the old ones away included. Your own house could be more or less: see yours from one photo.`,
    alt: 'Price card: 8 new white uPVC casement windows on a typical semi-detached house.',
    link: '/design?journey=windows', pinTitle: 'How much do 8 new windows cost in the UK?' },
  { kind: 'tip', slug: 'neighbours', eyebrow: 'Worth knowing',
    headline: 'Two neighbours. Same street. Same windows. Thousands apart.',
    sub: 'Prices for the same job vary a lot. Know roughly what yours should cost before anyone quotes.',
    caption: 'Two houses, same street, same windows — and quotes thousands of pounds apart. It happens all the time. A planning estimate before the first visit means you know what a fair price looks like.',
    alt: 'Text card: two neighbours, same street, same windows, thousands apart.',
    link: '/', pinTitle: 'Why window quotes vary by thousands' },
  { kind: 'price', slug: 'anthracite-vs-white', headline: 'White or anthracite?', detail: '8 uPVC casement windows',
    houseType: 'semi', compare: true,
    price: async () => ({ a: await glazingRange({ houseType: 'semi', count: 8 }), b: await glazingRange({ houseType: 'semi', count: 8, colourId: 'anthracite' }) }),
    labels: ['White', 'Anthracite grey'],
    caption: (p) => `Does anthracite cost more than white? On 8 uPVC casement windows on ${TYPE.semi}: white ${p.a}, anthracite ${p.b}. Fitted, inc. VAT.`,
    alt: 'Price comparison card: 8 white windows versus 8 anthracite windows on a typical semi.',
    link: '/design?journey=windows', pinTitle: 'Anthracite vs white windows: the price difference' },
  { kind: 'tip', slug: 'how-it-works', eyebrow: 'How it works',
    list: ['Take one photo of the front', 'Try windows, doors, walls and roof on it', 'See a costed estimate — no visit, no sales call'],
    headline: 'See it, price it, then decide.',
    caption: 'Three steps: one photo of the front, try new windows, doors, walls or roof on your own house, and see a costed planning estimate. No account, and no installer hears from you unless you ask.',
    alt: 'How it works: take a photo, try options on your house, see a costed estimate.',
    link: '/design', pinTitle: 'See new windows on your own house before you buy' },
  { kind: 'reveal', slug: 'composite-door-reveal', before: 'pbBefore', after: 'pbWhiteDoor',
    headline: 'Keep the windows. New front door.',
    sub: 'Not every job is the whole house — try just the door.',
    caption: 'Happy with your windows? Try just a new composite front door on your own house first.',
    alt: 'Before and after AI illustration: the same detached house with its white windows kept and a new composite front door.',
    link: '/design?journey=doors', pinTitle: 'New composite front door: before and after' },
  { kind: 'price', slug: 'composite-door-semi', headline: 'A composite front door', detail: 'supplied and fitted',
    houseType: 'semi', price: () => glazingRange({ houseType: 'semi', doorStyleId: 'composite' }),
    caption: (p) => `A composite front door on ${TYPE.semi}: ${p}, fitted, inc. VAT, with the old door taken away. See it on your own house first.`,
    alt: 'Price card: a composite front door on a typical semi-detached house.',
    link: '/design?journey=doors', pinTitle: 'Composite front door cost UK' },

  // ── week 2 ──
  { kind: 'tip', slug: 'questions-to-ask', eyebrow: 'Before you sign',
    list: ['Is the price itemised?', 'Is taking the old ones away included?', 'Is the installer FENSA or Certass registered?', 'Is the guarantee insurance-backed?', 'Is VAT included?'],
    headline: '5 questions to ask before you sign for new windows',
    caption: 'Five questions worth asking any window company before you sign: is the price itemised, is removal included, are they FENSA or Certass registered, is the guarantee insurance-backed, and is VAT in the figure?',
    alt: 'Checklist: five questions to ask before signing for new windows.',
    link: '/', pinTitle: '5 questions to ask before buying new windows' },
  { kind: 'reveal', slug: 'tile-hung-reveal', before: 'thBefore', after: 'thAfter',
    headline: 'Tile-hung house, anthracite windows.',
    sub: 'The tile-hanging stays; only the frames change.',
    caption: 'A tile-hung house with anthracite windows — the tiles stay exactly as they are. Try it on yours.',
    alt: 'Before and after AI illustration: a detached house with red tile-hanging, white windows then anthracite windows.',
    link: '/design?journey=windows', pinTitle: 'Tile-hung house with anthracite windows' },
  { kind: 'price', slug: '6-windows-terrace', headline: '6 new windows', detail: 'uPVC casement · white',
    houseType: 'terrace', price: () => glazingRange({ houseType: 'terrace', count: 6 }),
    caption: (p) => `6 new uPVC casement windows on ${TYPE.terrace}: ${p}, fitted, inc. VAT. Yours is priced from your own photo.`,
    alt: 'Price card: 6 new white uPVC windows on a typical mid-terrace house.',
    link: '/design?journey=windows', pinTitle: 'How much do new windows cost for a terrace house?' },
  { kind: 'tip', slug: 'planning-estimate', eyebrow: 'Plain English',
    headline: 'What is a planning estimate?',
    sub: 'A range for your house, from your photo — so you know the ballpark. The installer confirms the exact price after a survey.',
    caption: 'A planning estimate is a price range for your own house, worked out from your photo, so you know the ballpark before anyone visits. It is not a quotation: the installer confirms the exact figure after measuring.',
    alt: 'Text card explaining what a planning estimate is.',
    link: '/how-we-price', pinTitle: 'What is a planning estimate for home improvements?' },
  { kind: 'reveal', slug: 'black-or-anthracite', before: 'pbAnth', after: 'pbBlack', labels: ['Anthracite', 'Black'],
    headline: 'Anthracite or black?',
    sub: 'Side by side on the same house. Which would you pick?',
    caption: 'Anthracite grey or black? The same house, both ways. Which would you choose for yours?',
    alt: 'AI illustration comparing the same house with anthracite windows and with black windows.',
    link: '/design?journey=windows', pinTitle: 'Anthracite vs black windows on a red-brick house' },
  { kind: 'price', slug: '12-windows-detached', headline: '12 new windows', detail: 'uPVC casement · white',
    houseType: 'detached', price: () => glazingRange({ houseType: 'detached', count: 12 }),
    caption: (p) => `12 new uPVC casement windows on ${TYPE.detached}: ${p}, fitted, inc. VAT. See yours from one photo.`,
    alt: 'Price card: 12 new white uPVC windows on a typical detached house.',
    link: '/design?journey=windows', pinTitle: 'Cost of new windows for a detached house UK' },
  { kind: 'tip', slug: 'no-sales-call', eyebrow: 'How we work',
    headline: 'No account. No sales call unless you ask.',
    sub: 'See your house, see the price. An installer only hears from you if you ask for quotes.',
    caption: 'No account to make, nothing to cancel, and no installer hears from you unless you ask for quotes. See your house and the price first, in your own time.',
    alt: 'Text card: no account, no sales call unless you ask.',
    link: '/', pinTitle: 'See your home improvement price without a sales call' },

  // ── week 3 ──
  { kind: 'reveal', slug: '1930s-makeover', before: 'c30Before', after: 'c30Full',
    headline: 'A 1930s house, the whole front.',
    sub: 'Windows, door, roofline and roof — tried together on one photo.',
    caption: 'A 1930s house with anthracite windows, a new door, a light roofline and a grey roof — all tried on one photo before deciding which jobs to do.',
    alt: 'Before and after AI illustration of a 1930s detached house: new windows, door, roofline and grey roof.',
    link: '/design', pinTitle: '1930s house exterior makeover: before and after' },
  { kind: 'price', slug: 'roofline-semi', headline: 'Fascias, soffits & guttering', detail: 'the roofline, replaced',
    houseType: 'semi', price: () => exteriorRange({ houseType: 'semi', trimId: 'ink-trim' }),
    caption: (p) => `New fascias, soffits and guttering on ${TYPE.semi}: ${p}, inc. VAT, scaffolding included. See it on your own house first.`,
    alt: 'Price card: fascias, soffits and guttering on a typical semi-detached house.',
    link: '/design?journey=roofline', pinTitle: 'Fascia, soffit and guttering replacement cost UK' },
  { kind: 'tip', slug: 'what-is-roofline', eyebrow: 'Plain English',
    list: ['Fascia — the board along the roof edge that holds the gutter', 'Soffit — the panel underneath, closing the gap to the wall', 'Guttering — carries the rain to the downpipes'],
    headline: 'Fascias, soffits and guttering: what’s what?',
    caption: 'Fascia: the board along the roof edge that holds the gutter. Soffit: the panel underneath it. Guttering: carries rainwater to the downpipes. Together they are the roofline — usually replaced in one job, off one scaffold.',
    alt: 'Explainer: what fascias, soffits and guttering are.',
    link: '/design?journey=roofline', pinTitle: 'What are fascias and soffits?' },
  { kind: 'price', slug: 'upvc-door-semi', headline: 'A uPVC front door', detail: 'supplied and fitted',
    houseType: 'semi', price: () => glazingRange({ houseType: 'semi', doorStyleId: 'upvc' }),
    caption: (p) => `A uPVC front door on ${TYPE.semi}: ${p}, fitted, inc. VAT, old door taken away. Try styles on your own house.`,
    alt: 'Price card: a uPVC front door on a typical semi-detached house.',
    link: '/design?journey=doors', pinTitle: 'uPVC front door cost UK' },
  { kind: 'reveal', slug: 'cladding-reveal', before: 'c30Before', after: 'c30Clad',
    headline: 'Cladding upstairs, anthracite windows.',
    sub: 'Graphite cladding on the upper floor — tried before anyone quotes.',
    caption: 'Graphite cladding upstairs and anthracite windows on a 1930s house. See how it would look on yours.',
    alt: 'Before and after AI illustration: 1930s house with graphite cladding on the upper floor and anthracite windows.',
    link: '/design?journey=cladding', pinTitle: 'House cladding ideas: before and after' },
  { kind: 'tip', slug: 'scaffold', eyebrow: 'Worth knowing',
    headline: 'Is the scaffold in the price?',
    sub: 'Roof, roofline and render jobs need scaffolding. Ask whether it is in the quote — ours always is.',
    caption: 'Roof, roofline and wall jobs need scaffolding, and it is a real part of the cost. Always ask whether a quote includes it. Every Facet Pro estimate for those jobs does — and if you do several at once, the scaffold is only counted once.',
    alt: 'Text card: is scaffolding included in the price?',
    link: '/how-we-price', pinTitle: 'Is scaffolding included in a roof or render quote?' },
  { kind: 'price', slug: 'render-semi', headline: 'Rendering the walls', detail: 'Alabaster render',
    houseType: 'semi', price: () => exteriorRange({ houseType: 'semi', claddingId: 'alabaster' }),
    caption: (p) => `Rendering the walls of ${TYPE.semi}: ${p}, inc. VAT, scaffolding included. Try it on your own house first.`,
    alt: 'Price card: rendering the walls of a typical semi-detached house.',
    link: '/design?journey=cladding', pinTitle: 'House rendering cost UK' },

  // ── week 4 ──
  { kind: 'tip', slug: 'render-vs-cladding', eyebrow: 'Plain English',
    list: ['Render — a coat applied over the brick or block', 'Cladding — boards or panels fixed to the wall', 'Both change the look; both need scaffolding'],
    headline: 'Render or cladding: what’s the difference?',
    caption: 'Render is a coat applied over the brick or block. Cladding is boards or panels fixed to the wall. Both change the whole look of a house, and both need scaffolding. Try each on your own house.',
    alt: 'Explainer: the difference between render and cladding.',
    link: '/design?journey=cladding', pinTitle: 'Render vs cladding: what is the difference?' },
  { kind: 'reveal', slug: 'black-door-reveal', before: 'pbBefore', after: 'pbBlackDoor',
    headline: 'Black windows, new door.',
    sub: 'A bold change on a red-brick house.',
    caption: 'Black windows and a new composite door on a red-brick house. Bold — would you?',
    alt: 'Before and after AI illustration: red-brick detached house with black windows and a composite front door.',
    link: '/design?journey=windows', pinTitle: 'Black windows on a red-brick house' },
  { kind: 'price', slug: 'slate-roof-semi', headline: 'A new slate roof', detail: 'stripped and re-covered',
    houseType: 'semi', price: () => exteriorRange({ houseType: 'semi', roofId: 'slate-roof' }),
    caption: (p) => `A new slate roof on ${TYPE.semi}: ${p}, inc. VAT, scaffolding included. See it on your own house first.`,
    alt: 'Price card: a new slate roof on a typical semi-detached house.',
    link: '/design?journey=roof', pinTitle: 'New slate roof cost UK' },
  { kind: 'tip', slug: 'why-a-range', eyebrow: 'Plain English',
    headline: 'Why a range, not one price?',
    sub: 'Installers price the same job differently, and a photo can’t measure to the centimetre. The range is honest about both.',
    caption: 'Why do we show a range? Because installers price the same job differently, and a photo cannot measure to the centimetre. A range is honest about both — and the installer confirms the exact figure on survey.',
    alt: 'Text card: why a price range rather than one figure.',
    link: '/how-we-price', pinTitle: 'Why home improvement estimates are a range' },
  { kind: 'price', slug: 'bifold-semi', headline: 'Bifold doors', detail: 'up to 2.4 m wide',
    houseType: 'semi', price: () => glazingRange({ houseType: 'semi', doorStyleId: 'bifold' }),
    caption: (p) => `Bifold doors up to 2.4 m on ${TYPE.semi}: ${p}, fitted, inc. VAT.`,
    alt: 'Price card: bifold doors up to 2.4 metres on a typical semi-detached house.',
    link: '/design?journey=doors', pinTitle: 'Bifold doors cost UK' },
  { kind: 'tip', slug: 'door-ruler', eyebrow: 'How we measure',
    headline: 'Your front door is the ruler.',
    sub: 'Front doors are a standard height, so we use yours to size your windows and walls from the photo.',
    caption: 'How can one photo give a price? Front doors are a standard height, so we use yours as a ruler to size the windows and walls around it. An installer measures exactly on survey.',
    alt: 'Text card: we use your front door as a ruler to measure from your photo.',
    link: '/how-we-price', pinTitle: 'How to estimate window sizes from a photo' },

  { kind: 'tip', slug: 'why-we-built-it', eyebrow: 'Why Facet Pro',
    headline: '24 years selling windows. This is the tool I wanted homeowners to have.',
    sub: 'See your own house changed, and what it should cost, before anyone comes round.',
    caption: 'I have spent twenty-four years selling windows, doors and home improvements, and seen how differently similar homes get priced. Facet Pro gives you the picture and the ballpark first — before anyone comes round.',
    alt: 'Text card: 24 years selling windows; the tool for homeowners.',
    link: '/', pinTitle: 'See your home improvement price before a salesman visits' },

  // ── days 29–30 ──
  { kind: 'tip', slug: 'planning-permission', eyebrow: 'Worth knowing',
    headline: 'Do new windows need planning permission?',
    sub: 'Usually not for a house, if they look similar to the old ones. Listed buildings, conservation areas and flats can differ — check with your council.',
    caption: 'Do you need planning permission for new windows? For most houses, not if the new ones look similar to the old. Listed buildings, conservation areas and flats can be different, so check with your council if that is you.',
    alt: 'Text card: do new windows need planning permission?',
    link: '/', pinTitle: 'Do you need planning permission for new windows UK?' },
  { kind: 'reveal', slug: 'try-yours', before: 'pbBefore', after: 'pbDoor',
    headline: 'Now try it on yours.',
    sub: 'One photo of the front. Free. No sales call.',
    caption: 'You have seen it on ours — now try it on your own house. One photo of the front, free, and no sales call unless you ask.',
    alt: 'Before and after AI illustration: a red-brick house with anthracite windows and a composite front door.',
    link: '/design', pinTitle: 'See new windows and doors on your own house' },
];
